
services:
  docusaurus:
    build: .
    ports:
      - "9000:80"
    environment:
      API_KEY: xyz

  typesense:
    image: typesense/typesense:30.1
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command:
      - --data-dir
      - /data
      - --api-key
      - xyz
      - --enable-cors
    environment:
      - TYPESENSE_API_KEY=xyz
    # Optional: healthcheck
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  docsearch-scraper:
    image: typesense/docsearch-scraper
    container_name: docsearch-scraper
    environment:
      CONFIG: >
        {
          "index_name": "docusaurus-2",
          "typesenseCollectionName": "docusaurus-2",
          "start_urls": ["http://docusaurus"],
          "sitemap_urls": ["http://docusaurus/sitemap.xml"],
          "js_render": true,
          "selectors": {
            "default": {
              "lvl0": {
                "selector": "header h1",
                "defaultValue": "Documentation"
              },
              "lvl1": "article h1",
              "lvl2": "article h2",
              "text": "article p, article li"
            }
          }
        }

      TYPESENSE_API_KEY: xyz
      TYPESENSE_HOST: typesense
      TYPESENSE_PORT: "8108"
      TYPESENSE_PROTOCOL: http
    depends_on:
      - typesense
#        condition: service_healthy
    # Use extra_hosts to simulate host.docker.internal on Linux
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
  typesense-data: