// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generate the sidebar from the docs folder structure.
  // Ordering is controlled by sidebar_position in each page's frontmatter
  // and by _category_.json files in each folder.
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
